import './WhatsNew.css'
import { MERRY_EXTRAS } from '../data/content'

/**
 * "New in Merry" — extensible extras section.
 *
 * This section is intentionally data-driven and easy to extend. It renders
 * whatever cards live in the `MERRY_EXTRAS` array in src/data/content.ts.
 *
 * === HOW TO ADD A REAL FEATURE ===================================== *
 * You do NOT edit this file. Open src/data/content.ts, find MERRY_EXTRAS,
 * and replace a placeholder card (or push a new object) with your real
 * enhancement — set `placeholder: false` so the "Placeholder" badge is
 * dropped. The section updates automatically.
 * =================================================================== *
 *
 * The cards currently in MERRY_EXTRAS are clearly-marked PLACEHOLDERS on
 * purpose: the user said they added "a couple more things" without saying
 * what, so we do not fabricate specific feature claims here.
 */
function WhatsNew() {
  return (
    <section id="whats-new" aria-label="New in Merry" className="whats-new">
      <div className="container">
        <div className="section-heading">
          <h2>New in Merry</h2>
          <p className="section-heading__sub">
            The latest enhancements we've added — with room for more.
          </p>
        </div>

        <ul className="whats-new__grid">
          {MERRY_EXTRAS.map((extra) => (
            <li key={extra.title} className="whats-new__card">
              <div className="whats-new__card-head">
                <span className="whats-new__eyebrow">{extra.eyebrow}</span>
                {extra.placeholder && (
                  <span
                    className="whats-new__badge"
                    title="Replace this card in src/data/content.ts (MERRY_EXTRAS)"
                  >
                    Placeholder
                  </span>
                )}
              </div>
              <h3 className="whats-new__card-title">{extra.title}</h3>
              <p className="whats-new__card-body">{extra.body}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  )
}

export default WhatsNew
